# Generated by Django 6.0.7 on 2026-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genres', models.JSONField(default=list, help_text='Liste des noms de genres')),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0.0)),
                ('number_of_seasons', models.IntegerField(default=1)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('episode_run_time', models.IntegerField(default=0, help_text="Durée moyenne d'un épisode en minutes")),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('original_language', models.CharField(default='fr', max_length=10)),
                ('feature_vector', models.JSONField(default=list, help_text='Vecteur TF-IDF des synopsis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
    ]