# Generated by Django 6.0.7 on 2026-08-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shows.show')),
                ('show_rejected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_choices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
